# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bard-rake"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micah Geisel"]
  s.date = "2011-11-22"
  s.description = "Rake tasks for all bard projects.\n* Bootstrap projects\n* Database backup"
  s.email = "micah@botandrose.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bard-rake.gemspec",
    "lib/bard-rake.rb",
    "lib/bard/rake.rb",
    "lib/bard/rake/bootstrap.rb",
    "lib/bard/rake/bundler.rb",
    "lib/bard/rake/db.rb",
    "lib/bard/rake/railtie.rb",
    "spec/bard-rake_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/botandrose/bard-rake"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Rake tasks for all bard projects."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

